should still not commit

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,2 +1,11 @@
+#!/bin/sh
+. "$(dirname "$0")/_/husky.sh"
+
 pnpm format
-pnpm run coverage
+pnpm run coverage-check
+
+# Vérifier le code de sortie de vitest
+if [ $? -ne 0 ]; then
+  echo "Coverage is below threshold, aborting commit."
+  exit 1
+fi
